spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: 1q1q1q
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace